# Generated by Django 3.2.7 on 2021-09-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_nombre', models.CharField(max_length=100)),
                ('job_cuit', models.IntegerField(default=0, max_length=20, null=True)),
                ('job_direccion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('person_nombre', models.CharField(max_length=100)),
                ('person_apellido', models.CharField(max_length=100)),
                ('person_ciut', models.IntegerField(default=0, max_length=11, null=True)),
                ('person_email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
