# Generated by Django 3.2.7 on 2021-09-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_cuit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_ciut',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
