# Generated by Django 3.2.7 on 2021-09-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210917_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_cuit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_ciut',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_fecha', models.DateField(auto_now=True, null=True)),
                ('service_hora_desde', models.TimeField(auto_now=True, null=True)),
                ('service_hora_hasta', models.TimeField(auto_now=True, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='PriceDay',
            fields=[
                ('price_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price_day', models.IntegerField(choices=[('Lunes', 1), ('Martes', 2), ('Miercoles', 3), ('Jueves', 4), ('Viernes', 5), ('Sabado', 6), ('Domingo', 7)])),
                ('price_fecha_desde', models.DateField(auto_now=True, null=True)),
                ('price_fecha_hasta', models.DateField(auto_now=True, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
            ],
        ),
    ]
