# Generated by Django 3.2.7 on 2021-09-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210920_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceday',
            name='price_valor',
            field=models.IntegerField(default=0),
        ),
    ]
