# Generated by Django 3.2.7 on 2021-09-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_priceday_price_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceday',
            name='price_day',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')]),
        ),
    ]
