# Generated by Django 3.2.7 on 2021-09-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_priceday_price_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_fecha',
            field=models.DateField(null=True),
        ),
    ]
