# Generated by Django 3.2.7 on 2021-09-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_service_service_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceday',
            name='price_fecha_desde',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='priceday',
            name='price_fecha_hasta',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_hora_desde',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_hora_hasta',
            field=models.TimeField(null=True),
        ),
    ]
